# Generated by Django 5.2.2 on 2025-06-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_rename_description_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
